{% set data = load_setup_py_data(setup_file="../setup.py",
  from_recipe_dir=True) %}

package:
  name: openpiv
  version: {{ data.get('version') }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - imageio
    - matplotlib-base
    - scikit-image
    - scipy
    - natsort
    - tqdm
    - importlib_resources
    - arm_pyart

test:
  imports:
    - openpiv

about:
  home: https://github.com/openpiv/openpiv
  license: GPLv3
  license_file: LICENSE.txt
  summary: "Open Source Particle Image Velocimetry"
  doc_url: http://openpiv.readthedocs.io/
